### PR TITLE
feat: services section no mediaquery

### PR DESCRIPTION
**Pull request by RanBerkovich1**
I tried to use generic class names + didnt use media queries so it might not be perfect.

https://github.com/user-attachments/assets/180eef38-d8b4-4d66-a3e3-2afe680929c0

### CODE REVIEW

**Comment by alisey** [comment]
@RanBerkovich1 this PR undoes the work I've done in https://github.com/wixplosives/wireframe-snippets/pull/4. Brings back unused image files, reverts all fixes to the styling, breaks prefixing of classes, introduces both kebab-case and snake-case naming for the classes, even though we always use camel case for compatibility with different styling solutions.

I feel like I've spent time on pointless work and on writing comments that were not taken into account.

**Comment by RanBerkovich1** [comment]
@alisey I will fix it according to pr #4 although it's not needed anymore because I understood that WE CAN use mq's eventually as of last evening. 

I played with it as a practice to work with flex/grid with no mqs. I'll cancel this and I'm sorry for this whole loop. Thanks.

**Comment by alisey** [comment]
@RanBerkovich1 thanks. GitHub allows adding the "Draft" status to a PR to indicate that it is not in review and not ready for merging.

**Comment by RanBerkovich1** [comment]
Noted, thanks @alisey

**Pull request closed without merging**
